# Generated by Django 2.2.5 on 2021-05-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
